version: 2

# This is a Go library, so we skip building binaries
builds:
  - skip: true

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - 'typo'
  groups:
    - title: 'Features'
      regexp: '^feat:'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^fix:'
      order: 1
    - title: 'Performance'
      regexp: '^perf:'
      order: 2
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: agentflare-ai
    name: go-xsd
  prerelease: auto
  mode: replace
  draft: false
