name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    name: Pre-release Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run unit tests
        run: go test -v -race ./...

      - name: Build w3c_test
        run: |
          cd cmd/w3c_test
          go build -o w3c_test

      - name: Cache W3C Test Suite
        uses: actions/cache@v4
        with:
          path: /tmp/xsd-test-suite
          key: w3c-test-suite-release
          restore-keys: |
            w3c-test-suite-

      - name: Run W3C conformance tests
        run: |
          cd cmd/w3c_test
          ./w3c_test --auto-download --analyze --output w3c-results.txt
          cat w3c-results.txt

      - name: Upload W3C results
        uses: actions/upload-artifact@v4
        with:
          name: w3c-conformance-results
          path: cmd/w3c_test/w3c-results.txt
          retention-days: 90

  goreleaser:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
